name_or_path: openlm-research/open_llama_3b_v2
tokenizer_name_or_path: null
is_peft: true
peft_model_name: sachith-surge/open-llama-v2-lamini-orca-evol-guanaco-qlora-checkpoint
archive: null
block_name: LlamaDecoderLayer

policy_dtype: float32
fsdp_policy_mp: null
reference_dtype: float16